# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=record-query

matrix:
  include:
    # Linux
    - env: TARGET=i686-unknown-linux-gnu DISABLE_TESTS=1
      rust: stable
    - env: TARGET=i686-unknown-linux-musl
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu GEN_JSDOC=1
      rust: stable
    - env: TARGET=x86_64-unknown-linux-musl
      rust: stable

    # OSX
    - env: TARGET=i686-apple-darwin DISABLE_TESTS=1
      rust: stable
      os: osx
      osx_image: xcode8
    - env: TARGET=x86_64-apple-darwin
      rust: stable
      os: osx
      osx_image: xcode8

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
      rust: stable
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust: stable
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
      rust: stable

    # Other architectures
    - env: TARGET=aarch64-unknown-linux-gnu
      rust: stable
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: stable
    - env: TARGET=mips-unknown-linux-gnu
      rust: stable
    - env: TARGET=mips64-unknown-linux-gnuabi64
      rust: stable
    - env: TARGET=mips64el-unknown-linux-gnuabi64
      rust: stable
    - env: TARGET=mipsel-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64le-unknown-linux-gnu
      rust: stable
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
      rust: stable

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

  allow_failures:
    # Linux
    - env: TARGET=i686-unknown-linux-musl
      rust: stable
    - env: TARGET=x86_64-unknown-linux-musl
      rust: stable

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
      rust: stable
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust: stable
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
      rust: stable

    # Other architectures
    - env: TARGET=aarch64-unknown-linux-gnu
      rust: stable
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: stable
    - env: TARGET=mips-unknown-linux-gnu
      rust: stable
    - env: TARGET=mips64-unknown-linux-gnuabi64
      rust: stable
    - env: TARGET=mips64el-unknown-linux-gnuabi64
      rust: stable
    - env: TARGET=mipsel-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64le-unknown-linux-gnu
      rust: stable
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
      rust: stable

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install: set -e

install:
  - ./ci/install.sh

script:
  - ./ci/script.sh

after_script: set +e

before_deploy:
  - ./ci/before_deploy.sh

deploy:
  - api_key: "${GITHUB_TOKEN}"
    file_glob: true
    file: target/deploy/$CRATE_NAME-$TRAVIS_TAG-$TARGET.*
    on:
      condition: $TRAVIS_RUST_VERSION = stable
      tags: true
    provider: releases
    skip_cleanup: true
  - provider: s3
    access_key_id: AKIAIMXXFE4ETRSISAEA
    secret_access_key:
      secure: "BwXmKjyKJVzmBp9GyJ0raBrJP1cHZ8LYyUxIlHzhb7Zfxlot/R5HwnNKqYlu6QJb0VBL+vcFjzujHljvlPSu/fLFlg4MNc36l3IeowOchvZpv+2+72IgJCJgxC+d7s0Al/TILB4htYVwoIAAvO99HerKKX91M2TeCyEoYIK1PmYjw6c0gZo5CifUe9EISFqIzuUGysZsZFCsHF0purhIAIWBBJjgu35XLluvu+kZ1bJ22Fqvsz2x1MUyyNHV4pNw6gYwC4CSBwACuu2aQDY7i+ZXU6ubSyK5P495rElWqMpMtMVg0oxH+UAsdw4La2DwxkF8dc/4w4eYaix7ucXrV1n24M34nzm4GwZ3/n4ZANaRAtl6zxhTPk5UadEX5PAOAxPsTPDJYQPSU/ZkbdUsYm6YhJtw/HDQOAkwhrZs2PibVyM6JB34/AsJrryl+yZ+By7M2AOnDcLWAvYroqFVW316yIe1x4EJW9loknqNCseDGEHCqtAjX5tFB3n7h8w+p2VpoaR23AM1BoOUEuWzfQZtCULKSZFwFDlj3pnJAdC2zqojtr87zNcqUX+XMy7YpoLEVGetG8zpAYmKXE8r7jNrSMOagBph90ThN+D9Zjkku5p9xH2Xw2kRhZdY56JrhJApotWJ8j3Gr6dt8rRAssa8E388Xz+EMAC34fo2tr8="
    bucket: record-query
    region: eu-west-1
    skip_cleanup: true
    local_dir: target/deploy
    upload-dir: record-query
    cache_control: "max-age=3600"
    on:
      condition: $TRAVIS_RUST_VERSION = stable
      repo: dflemstr/rq

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
