[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
build = "build.rs"
categories = ["command-line-interface", "command-line-utilities", "development-tools", "text-processing", "value-formatting"]
description = "A tool for doing record analysis and transformation"
documentation = "https://github.com/dflemstr/rq/blob/master/README.md"
homepage = "https://github.com/dflemstr/rq"
keywords = ["command-line-tool", "cli", "javascript", "record", "query"]
license = "Apache-2.0"
name = "record-query"
readme = "README.md"
repository = "https://github.com/dflemstr/rq"
version = "0.10.4"

[badges]

[badges.travis-ci]
branch = "master"
repository = "dflemstr/rq"

[build-dependencies]
env_logger = "0.3.5"
regex = "0.2.1"

[dependencies]
ansi_term = "0.9.0"
docopt = "0.7.0"
dtoa = "0.4.1"
env_logger = "0.4.0"
error-chain = "0.9.0"
glob = "0.2.11"
itoa = "0.3.1"
log = "0.3.6"
nix = "0.7.0"
ordered-float = "0.4.0"
pest = "0.4.0"
protobuf = "1.0.24"
rmp = "0.8.2"
rmpv = "0.2.0"
rustc-serialize = "0.3.21"
serde = "0.9.7"
serde-hjson = "0.8.1"
serde-protobuf = "0.5.0"
serde_cbor = "0.5.0"
serde_json = "0.9.6"
serde_yaml = "0.6.0"
xdg-basedir = "1.0.0"
yaml-rust = "0.3.5"
csv = "1"
failure = "0.1.3"

[dependencies.toml]
features = ["serde"]
version = "0.3.0"

[dependencies.linked-hash-map]
features = ["serde_impl"]
version = "0.4.2"

[dependencies.v8]
version = "0.9.1"
optional = true

[dependencies.avro-rs]
version = "0.6.2"
features = ["snappy"]

[features]
shared = ["v8/shared"]
default = ["v8"]

[profile]

[profile.release]
lto = true
